#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $DB_USER;
  GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_USER;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $DB_USER;

  ALTER SYSTEM SET maintenance_work_mem = '2GB';
  ALTER SYSTEM SET max_wal_size = '10GB';
  ALTER SYSTEM SET checkpoint_timeout = '30min';
  SELECT pg_reload_conf();
EOSQL
