// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: coupon.sql

package dbgen

import (
	"context"
)

const getCouponByID = `-- name: GetCouponByID :one
SELECT id 
FROM coupons
WHERE id = $1
`

// Get Coupon by ID
func (q *Queries) GetCouponByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCouponByID, id)
	err := row.Scan(&id)
	return id, err
}
