// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql"

	"github.com/google/uuid"
)

type Coupon struct {
	ID string
}

type Order struct {
	ID         uuid.UUID
	CouponCode sql.NullString
	CreatedAt  int64
}

type OrderProduct struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
}

type Product struct {
	ID        uuid.UUID
	Name      string
	Category  sql.NullString
	Price     float64
	CreatedAt int64
}
